ARG ORIGINAL_IMAGE_NAME
FROM ${ORIGINAL_IMAGE_NAME}

ARG MOUNT_DEST
ARG ENTRY_PATH

COPY . ${MOUNT_DEST}
RUN chmod +x ${MOUNT_DEST}/entrypoint.sh

WORKDIR ${MOUNT_DEST}/${ENTRY_PATH}

ENTRYPOINT [ "/terraform/entrypoint.sh" ]
